AUTH_HOST: 'http://auth.dev'
AUTH_APP_ID:
AUTH_APP_SECRET:

LDAP_HOST:
LDAP_USER:
LDAP_PASS:

DOMAIN:
MAILER_SENDER: 'contacts.dev'
SECRET_KEY_BASE:
SMTP_SERVER:

EXCHANGE_HOST:
EXCHANGE_USER:
EXCHANGE_PASS:
