default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: contact_manager_app
  host:
  username:
  password:

test:
  <<: *default
  database: test_contact_manager_app

production:
  <<: *default
